title: Jiatong Su
description: GIS • Data Visualization • Urban Analytics
logo: /images/IMG_3083.jpg
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
minimal_mistakes_skin: default
paginate: 5

author:
  name: Jiatong Su
  links:
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/jiatong-su-415b71216
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/sujiatong

# 卡片式作品集合頁
collections:
  projects:
    output: true
    permalink: /projects/:path/
defaults:
  - scope: { path: "", type: "projects" }
    values:
      layout: single
      author_profile: true
      classes: wide
